### ISSUE TITLE
Access denied exception while stopping service

### ISSUE THREAD

**Issue by PavolHocko** [beshu-tech/readonlyrest-docs#16]
Hi,
I am using elasticsearch-oss-6.5.0 with readonlyrest-1.16.29_es6.5.0. When I stop running elasticsearch service I get this error. I am using java - "jre1.8.0_181" I also try OpenJDK "jdk-10.0.2" and "jdk-11.0.1". Still same error. Runing ES without readonlyrest working correct also old readonlyrest-1.16.29_es6.4.3 + elasticsearch-oss-6.4.3 working correct. Any idea?

`[2018-11-26T10:37:14,138][ERROR][i.n.u.c.D.rejectedExecution] [w6u2Laz] Failed to submit a listener notification task. Event loop shut down?
java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "setContextClassLoader")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472) ~[?:?]
	at java.security.AccessController.checkPermission(AccessController.java:895) ~[?:?]
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:335) ~[?:?]
	at java.lang.Thread.setContextClassLoader(Thread.java:1570) ~[?:?]
	at io.netty.util.concurrent.GlobalEventExecutor$2.run(GlobalEventExecutor.java:228) ~[netty-common-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.util.concurrent.GlobalEventExecutor$2.run(GlobalEventExecutor.java:225) ~[netty-common-4.1.30.Final.jar:4.1.30.Final]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at io.netty.util.concurrent.GlobalEventExecutor.startThread(GlobalEventExecutor.java:225) ~[netty-common-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.util.concurrent.GlobalEventExecutor.execute(GlobalEventExecutor.java:213) ~[netty-common-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:768) [netty-common-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:432) [netty-common-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:94) [netty-common-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:939) [netty-common-4.1.30.Final.jar:4.1.30.Final]
	at java.lang.Thread.run(Thread.java:844) [?:?]
`

**Comment by sscarduzio** [comment]
Can you try to edit `plugins/readonlyrest/plugin-security.policy` and add the following line?

```
  permission java.lang.RuntimePermission "setContextClassLoader";
```

Please tell me if it worked

**Comment by PavolHocko** [comment]
It works! Thank you :)

**Comment by sscarduzio** [comment]
yeah will be in next one
